"""created posts tables and updated foreign keys for quests and user v5

Revision ID: 0f37e5c19ac7
Revises: 49a2a4e45229
Create Date: 2024-10-22 19:14:10.436441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f37e5c19ac7'
down_revision: Union[str, None] = '49a2a4e45229'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
