"""added nullable to is_active in events

Revision ID: 1d838c4e5f56
Revises: c4aec4bd686b
Create Date: 2024-10-16 23:42:57.279231

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d838c4e5f56'
down_revision: Union[str, None] = 'c4aec4bd686b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
