"""changed name to is_active in events table

Revision ID: 439145ad5818
Revises: 1d838c4e5f56
Create Date: 2024-10-16 23:46:04.666225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '439145ad5818'
down_revision: Union[str, None] = '1d838c4e5f56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.drop_column('events', 'isActive')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('isActive', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('events', 'is_active')
    # ### end Alembic commands ###
