"""created posts tables and updated foreign keys for quests and user v4

Revision ID: 49a2a4e45229
Revises: e6c31c1c63b7
Create Date: 2024-10-22 19:07:05.467897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49a2a4e45229'
down_revision: Union[str, None] = 'e6c31c1c63b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
