"""created posts tables and updated foreign keys for quests and user

Revision ID: bdd1356d8b57
Revises: 4143ac6bd9e4
Create Date: 2024-10-22 18:20:47.777710

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bdd1356d8b57'
down_revision: Union[str, None] = '4143ac6bd9e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
