"""added columns for color adn image to quests

Revision ID: e3f135462536
Revises: 0f37e5c19ac7
Create Date: 2024-10-26 03:16:32.993272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3f135462536'
down_revision: Union[str, None] = '0f37e5c19ac7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quests', sa.Column('image', sa.String(), nullable=True))
    op.add_column('quests', sa.Column('color', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quests', 'color')
    op.drop_column('quests', 'image')
    # ### end Alembic commands ###
