"""created posts tables and updated foreign keys for quests and user v3

Revision ID: e6c31c1c63b7
Revises: c567eba359f2
Create Date: 2024-10-22 19:03:40.754799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6c31c1c63b7'
down_revision: Union[str, None] = 'c567eba359f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
